### ISSUE TITLE
[APP] GIMP

### ISSUE THREAD

**Issue by Albin-Xavier** [FlotterCodername/superelixier-updater#37]
### App name
GIMP

### App description
Image editor

### Hosted at
<Click appropriate box after submitting issue>

- [ ] AppVeyor
- [ ] GitHub
- [ ] Other service: SERVICE_NAME_HERE
- [x] Project website

URL: 
<AppVeyor or GitHub is preferred over project websites>https://www.gimp.org/downloads/

**Comment by Albin-Xavier** [comment]
Realized after posting that this is not actually a portable program. Sorry for bothering you.

**Comment by FlotterCodername** [comment]
No worries!
Actually, not even all the apps available now are actually portable archives. I have some cases where it just extracts from an InnoSetup installer (exe) or a self-extracting archive. Always fine to ask for installer based stuff.
IIRC when I tried to add GIMP a while back, the problem was not the exe installer, but that I'd need special handling for the redirect of the download. I could be wrong, though.
